### ISSUE TITLE
RTX 5090 / 595.58.03-p2p: vLLM TP=2 crashes only when custom-all-reduce + CUDA graphs are both enabled

### ISSUE THREAD

**Issue by himekifee** [aikitoria/open-gpu-kernel-modules#21]
### NVIDIA Open GPU Kernel Modules Version

595.58.03

### Please confirm this issue does not happen with the proprietary driver (of the same version). This issue tracker is only for bugs specific to the open kernel driver.

- [ ] I confirm that this does not happen with the proprietary driver package.

### Operating System and Version

Talos OS v1.13.0-beta.1

### Kernel Release

6.18.19-talos

### Please confirm you are running a stable release kernel (e.g. not a -rc). We do not accept bug reports for unreleased kernels.

- [x] I am running on a stable kernel release.

### Hardware: GPU

RTX 5090

### Describe the bug

I’m seeing a reproducible crash with the P2P hack on **RTX 5090 PCIe (PHB)** that does **not** happen on stock NVIDIA **595.58.03**.

## Environment

- GPUs: **2× RTX 5090** (from a 4×5090 node)
- Topology: **PHB**
- Driver base: **595.58.03**
- CUDA: **13.0**
- PyTorch: **2.11.0+cu130**
- NCCL: **2.28.9+cuda13.0**
- vLLM: **0.19.1rc1.dev118**

Hack config:

```text
OpenRmEnableUnsupportedGpus=1
DmaRemapPeerMmio=1
RegistryDwords="ForceP2P=17;RMForceP2PType=1;RMPcieP2PType=1;PeerMappingOverride=1;RMForceStaticBar1=1"
```

## Situation

With the patched P2P driver, this vLLM command crashes during startup:

```bash
vllm serve /models/Qwen3.5-35B-A3B-NVFP4 \
  --host 0.0.0.0 \
  --port 8001 \
  --served-model-name qwen3.5-35b-a3b \
  --tensor-parallel-size 2 \
  --max-model-len 16384 \
  --gpu-memory-utilization 0.88 \
  --speculative-config '{"method":"mtp","num_speculative_tokens":6}' \
  --max-num-seqs 20 \
  --enable-log-requests \
  --language-model-only \
  --aggregate-engine-logging \
  --enable-sleep-mode \
  --api-server-count 1 \
  --no-enable-prefix-caching
```

The crash happens right after:

```text
[kv_cache_utils.py:829] Overriding num_gpu_blocks=0 with num_gpu_blocks_override=272
[gpu_model_runner.py:5893] Profiling CUDA graph memory: PIECEWISE=33 (largest=259), FULL=18 (largest=140)
```

Then:

```text
Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:455 'an illegal memory access was encountered'
Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:455 'an illegal memory access was encountered'
```

And kernel log shows `NVRM: Xid (PCI:0000:03:00): 31, pid=130010, name=python3, channel 0x00000002, intr 00000000. MMU Fault: ENGINE GRAPHICS GPC0 GPCCLIENT_T1_4 faulted @ 0x7b4b_49707000. Fault is of type FAULT_PDE ACCESS_TYPE_VIRT_READ` on both GPUs.

## Very important matrix

This is the key discriminator:

- default run: **FAIL**
- add `--enforce-eager`: **PASS**
- remove `--enforce-eager`, add `--disable-custom-all-reduce`: **PASS**
- remove `--disable-custom-all-reduce`: **FAIL again**
- same workload on **stock 595.58.03**: **PASS**

So the failure requires **both**:

1. **CUDA graphs enabled**
2. **vLLM custom all-reduce enabled**

It is **not** a generic TP=2 failure.

## Why I think this is in the hacked driver

On the patched driver, these all pass:

- `cudaDeviceCanAccessPeer`
- `cudaDeviceEnablePeerAccess`
- `p2pBandwidthLatencyTest`
- `simpleIPC`
- vLLM `can_actually_p2p`
- NCCL all_reduce completes

But vLLM still crashes only in the **graph + custom-all-reduce** path.

So this looks like:

> basic P2P / basic IPC works, but the patched driver breaks the **graph-captured peer/IPC registration path** used by vLLM custom-all-reduce.

From vLLM source, the crash site `custom_all_reduce.cuh:455` is in the graph-only metadata path around:

- `cuPointerGetAttribute(CU_POINTER_ATTRIBUTE_RANGE_START_ADDR, ...)`
- `cudaIpcGetMemHandle(...)`

This path is only exercised when **graphs + custom all-reduce** are both active.

## Additional evidence

On the patched driver:

- `nvidia-smi topo -p2p r` / `w`: **OK**
- BAR1 per GPU: **32 GiB**
- `simpleIPC`: **PASS**
- NCCL log shows:

  ```text
  isAllCudaP2p=1
  isAllDirectP2p=0
  via SHM/direct/direct
  ```

  so NCCL is conservative and does not trust direct P2P fully.

Also, I built the patched source standalone on a stock host and compared built modules against stock 595.58.03:

- **only `nvidia.ko` differs**
- `nvidia-uvm.ko`, `nvidia-drm.ko`, `nvidia-modeset.ko`, `nvidia-peermem.ko` match stock

So the suspect is narrowed to **core `nvidia.ko` changes**, not UVM/DRM/etc.

## Current suspect

The most likely issue is in the hacked repo’s **core BAR1 / peer-mapping path in `nvidia.ko`**, especially anything that:

- forces BAR1 P2P capability on RTX 5090 PCIe
- overrides peer mapping checks
- changes graph-captured allocation export/import behavior
- makes `cudaIpcGetMemHandle` / `cudaIpcOpenMemHandle` appear valid for buffers that later fault under real access

The highest-suspicion areas are the `nvidia.ko` patches that:

- force BAR1/P2P capability reporting
- override peer mapping support
- route non-datacenter GPUs into BAR1 P2P code paths

In other words, this does **not** look like “P2P completely broken”; it looks more like:

> the hacked driver enables a peer/BAR1 path that survives small tests, but becomes invalid when vLLM registers graph-captured buffers for custom all-reduce.

### To Reproduce

Run above vllm command with p2p driver

### Bug Incidence

Always

### nvidia-bug-report.log.gz

[nvidia-bug-report.log.gz](https://github.com/user-attachments/files/26646455/nvidia-bug-report.log.gz)
Fake empty log gz... Can't get that easily on talos...Will try to get it if really needed

**Comment by aikitoria** [comment]
Custom all reduce is usually something intended to be used with nvlink and might rely on APIs only available with that or rely on nvswitches being present etc. Are you sure this code is sensible to run with pcie p2p to begin with?

A brief look at the docs for `cudaIpcOpenMemHandle` suggests `IPC functionality is restricted to devices with support for unified addressing on Linux operating systems` but 5090s should pass this requirement.

I only use single process P2P in my own projects. Try having your agent build increasingly advanced test cases with access to the driver source to add debug logs to find the cause

**Comment by himekifee** [comment]
Not 100% sure, but without the hugepage improvement introduced in the recent commit seems fixed it. Will investigate further.

**Comment by himekifee** [comment]
btw custom all reduce is enabled by default in vllm so even run normally, the crash would be encountered.

**Comment by aikitoria** [comment]
That's interesting. Perhaps that change is still half baked.

**Comment by aikitoria** [comment]
I tried to reproduce the issue locally:

1. Pulled vllm/vllm-openai:latest (v0.19.0) Docker image
2. Ran the model Sehyo/Qwen3.5-35B-A3B-NVFP4 with TP=2 on 2x RTX 5090
3. Used default settings (CUDA graphs + custom all-reduce both on)
4. Did not use any of the extra registry dwords (ForceP2P=17, RMForceStaticBar1=1, etc.) as they should not be required with the patched driver

vLLM started just fine, captured the graphs, and replied to inference requests with sensible responses. It doesn't use huge pages, so it should not be affected by that commit at all. Do you have some custom configuration to force the container to use huge pages?

**Comment by himekifee** [comment]
> I tried to reproduce the issue locally:
> 
>     1. Pulled vllm/vllm-openai:latest (v0.19.0) Docker image
> 
>     2. Ran the model Sehyo/Qwen3.5-35B-A3B-NVFP4 with TP=2 on 2x RTX 5090
> 
>     3. Used default settings (CUDA graphs + custom all-reduce both on)
> 
>     4. Did not use any of the extra registry dwords (ForceP2P=17, RMForceStaticBar1=1, etc.) as they should not be required with the patched driver
> 
> 
> vLLM started just fine, captured the graphs, and replied to inference requests with sensible responses. It doesn't use huge pages, so it should not be affected by that commit at all. Do you have some custom configuration to force the container to use huge pages?

Ya I have a running diagnostic procedure. Later found out hugepage is not the issue, it is deeper in a combo of vllm cuda graph cache, dp/tp, module nvreg etc... Too many factors, but I managed to narrow down to the Non sense AI generated `NVreg_RegistryDwords="ForceP2P=17;RMForceP2PType=1;RMPcieP2PType=1;PeerMappingOverride=1;RMForceStaticBar1=1`. Have absolute no idea why it proposed in the first place, but for some reason talos p2p really does not work without those dwrods, so I'm bisecting what actually matters. Will get back to you later.

**Comment by aikitoria** [comment]
I haven't used talos so I don't know what's special about it, my server I use for all the experiments runs Debian 14/testing and it works fine there.

**Comment by himekifee** [comment]
Thanks again for working on this.

After 5 days of auto debugging spanning across 332 gpt-5.4-xhigh/claude-opus-4.6 subagent sessions, I now have a **standalone CUDA repro** attached (`poc.cu`) that does **not** depend on vLLM or Python. Could you try it on your setup and see whether you get the same split?

[poc.zip](https://github.com/user-attachments/files/26805080/poc.zip)
## What I see on my side
### 1. Low-level P2P itself looks healthy on the patched module
On the patched setup, the basic peer path looks fine:
- `nvidia-smi topo -p2p r` = `OK`
- `p2pBandwidthLatencyTest` passes
- `simpleP2P` passes
So this does **not** look like a basic "P2P is broken" problem.
### 2. The standalone repro still splits stock vs patched
With the attached `poc.cu`:
- **stock module, no override** -> **passes**
- **patched module** -> **fails**
The interesting part is that the repro has two modes:
- **broad / stale-metadata path**
- **narrow / fresh-metadata path**
On the patched P2P setup, the result is:
- **broad**: fails
- **narrow**: passes
On stock/no-override, it falls back cleanly and passes.
That makes me think the failure is not the peer copy path itself, but something about **registration / IPC-handle lifetime / metadata freshness** once the direct peer path is actually working.
## Why I suspect this may be a vLLM-side bug
The shape I found in current upstream vLLM still seems important.
On upstream `main` at commit [`edc3648966e30e8bf5f34edeee50027ddd79dc16`](https://github.com/vllm-project/vllm/commit/edc3648966e30e8bf5f34edeee50027ddd79dc16):
- [`GroupCoordinator.graph_capture()` in `vllm/distributed/parallel_state.py`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/distributed/parallel_state.py#L463-L490) still owns `ca_comm.capture()` at the **outer** boundary  
  (`ca_comm.capture()` is at [line 481](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/distributed/parallel_state.py#L481))
- the broader graph-capture flow is still wrapped outside the real inner graph bodies:
  - [`vllm/v1/worker/gpu/cudagraph_utils.py#L190-L223`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/v1/worker/gpu/cudagraph_utils.py#L190-L223)
  - [`vllm/v1/worker/gpu_model_runner.py#L6031-L6033`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/v1/worker/gpu_model_runner.py#L6031-L6033)
- the actual inner `torch.cuda.graph(...)` sites happen later and more narrowly, for example in:
  - [`vllm/compilation/cuda_graph.py`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/compilation/cuda_graph.py)
  - [`vllm/v1/worker/gpu_ubatch_wrapper.py`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/v1/worker/gpu_ubatch_wrapper.py)
  - [`vllm/v1/worker/gpu/cudagraph_utils.py`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/v1/worker/gpu/cudagraph_utils.py)
  - [`vllm/v1/worker/encoder_cudagraph.py`](https://github.com/vllm-project/vllm/blob/edc3648966e30e8bf5f34edeee50027ddd79dc16/vllm/v1/worker/encoder_cudagraph.py)
In other words, CAR capture still appears to be attached to a **broader outer scope** than the actual inner graph bodies.
That lines up with the behavior in my standalone repro:
- **broad / stale handle path** -> fails on patched direct P2P
- **narrow / fresh handle path** -> passes
Also, on my side, latest upstream vLLM on the patched module was:
- **RED** in unpatched upstream form
- **GREEN** after narrowing CAR capture to the actual inner `torch.cuda.graph(...)` sites
For a possibly related upstream bug class, I also noticed this existing issue:
- [vLLM issue #28334](https://github.com/vllm-project/vllm/issues/28334)
So my current working hypothesis is:
> the patched module is exposing a stricter / more real direct peer-memory path, and that makes an existing **vLLM-side capture-boundary / graph-buffer registration lifetime bug** visible.
Not saying this proves the driver is perfect, but at this point it no longer looks like a simple “your P2P patch is broken” issue to me.
## Could you check this on your setup?
If you have time, could you please try the attached `poc.cu` and see whether you also get:
- stock/no-override -> pass
- patched P2P -> broad fails, narrow passes
If you see the same thing, do you agree this looks more like a **vLLM-side bug** (CAR capture / graph-buffer registration lifetime / stale IPC metadata) than a fundamental bug in the P2P module itself?
If you agree, I’ll open an upstream vLLM issue and include:
- the standalone repro
- the stock vs patched results
- the upstream source links above

Thanks — even just a yes/no on whether this reproduces similarly on your machine would already help a lot.

**Comment by aikitoria** [comment]
Had a look through the POC.

It isn't actually reproducing anything vLLM does. In "broad" mode you allocate a buffer, export an IPC handle, then free the buffer, and send the stale handle to the peer. That's just use-after-free, no real code does this. vLLM's custom all-reduce allocates its signal and data buffers once in `CustomAllreduce.__init__` and keeps them around for the whole process. `register_graph_buffers()` exports handles from live torch tensors after capture finishes. Nothing ever frees a buffer and then sends its handle.

The stock pass is also misleading. Without peer access the child can't open any handle, so every open fails, and your check falls back to `local_verify_ok`, which only asks whether the parent wrote its own local buffer. That's always true no matter which driver is loaded.

So the reproducer is broken. It only produces the split because you wrote it that way.

**Comment by naveline67** [comment]
@himekifee 

can you use this and retry  ?


`git clone nccl and build`

then 

```
VLLM_SKIP_P2P_CHECK=1 \
CUDA_VISIBLE_DEVICES=0,1 \
VLLM_NCCL_SO_PATH=/home/xxx/nccl/build/lib/ \libnccl.so.2.30.3 \
NCCL_P2P_LEVEL=SYS \
vllm serve ...

```


please keep in mind ~~vllm~~ nccl will NOT use p2p that is NOT nvlink... i know everyone on reddit is using disable custom all reduce and do not understand why....

**Comment by himekifee** [comment]
Can't reproduce anymore. Close.
